# Generated by Django 5.1.5 on 2025-01-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('system_user', '0002_systemuser_created_on_systemuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='system_user_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='system_user_permissions', to='auth.permission'),
        ),
    ]
